package it.desimone.risiko.torneo.utils;

public enum PrioritaSorteggio {

	 MINIMIZZAZIONE_PARTECIPAZIONE_TAVOLO_DA_3
	,MINIMIZZAZIONE_PARTECIPAZIONE_TAVOLO_DA_5
	,IMPEDITO_STESSO_CLUB
	,IMPEDITO_STESSO_CLUB_CONSIDERANDO_I_FISSI
	,IMPEDITO_STESSO_CLUB_NON_CONSIDERANDO_I_FISSI
	,IMPEDITA_STESSA_REGIONE
	,MINIMIZZAZIONE_SCONTRI_DIRETTI
	,VINCITORI_SEPARATI
	,ALLA_SVIZZERA
	,ALLA_GRECA
	,MINIMIZZAZIONE_SCONTRI_DIRETTI_TRA_CLUB
	,MINIMIZZAZIONE_SCONTRI_DIRETTI_GIOCATORE_CLUB
}
