package it.desimone.risiko.torneo.utils;

import it.desimone.risiko.torneo.dto.ProvinciaDTO;

import java.util.List;

public class ProvincieLoader {

	private final static java.util.List<ProvinciaDTO> provincie = new java.util.ArrayList<ProvinciaDTO>();
	
	public static final ProvinciaDTO 		TO		 = new ProvinciaDTO("		TO		".trim(),	1	,"		Torino		".trim());	
	public static final ProvinciaDTO 		VC		 = new ProvinciaDTO("		VC		".trim(),	1	,"		Vercelli		".trim());	
	public static final ProvinciaDTO 		NO		 = new ProvinciaDTO("		NO		".trim(),	1	,"		Novara		".trim());	
	public static final ProvinciaDTO 		CN		 = new ProvinciaDTO("		CN		".trim(),	1	,"		Cuneo		".trim());	
	public static final ProvinciaDTO 		AT		 = new ProvinciaDTO("		AT		".trim(),	1	,"		Asti		".trim());	
	public static final ProvinciaDTO 		AL		 = new ProvinciaDTO("		AL		".trim(),	1	,"		Alessandria		".trim());	
	public static final ProvinciaDTO 		BI		 = new ProvinciaDTO("		BI		".trim(),	1	,"		Biella		".trim());	
	public static final ProvinciaDTO 		VB		 = new ProvinciaDTO("		VB		".trim(),	1	,"		Verbano-Cusio-Ossola		".trim());	
	public static final ProvinciaDTO 		AO		 = new ProvinciaDTO("		AO		".trim(),	2	,"		Valle d'Aosta/Vallée d'Aoste		".trim());	
	public static final ProvinciaDTO 		VA		 = new ProvinciaDTO("		VA		".trim(),	3	,"		Varese		".trim());	
	public static final ProvinciaDTO 		CO		 = new ProvinciaDTO("		CO		".trim(),	3	,"		Como		".trim());	
	public static final ProvinciaDTO 		SO		 = new ProvinciaDTO("		SO		".trim(),	3	,"		Sondrio		".trim());	
	public static final ProvinciaDTO 		MI		 = new ProvinciaDTO("		MI		".trim(),	3	,"		Milano		".trim());	
	public static final ProvinciaDTO 		BG		 = new ProvinciaDTO("		BG		".trim(),	3	,"		Bergamo		".trim());	
	public static final ProvinciaDTO 		BS		 = new ProvinciaDTO("		BS		".trim(),	3	,"		Brescia		".trim());	
	public static final ProvinciaDTO 		PV		 = new ProvinciaDTO("		PV		".trim(),	3	,"		Pavia		".trim());	
	public static final ProvinciaDTO 		CR		 = new ProvinciaDTO("		CR		".trim(),	3	,"		Cremona		".trim());	
	public static final ProvinciaDTO 		MN		 = new ProvinciaDTO("		MN		".trim(),	3	,"		Mantova		".trim());	
	public static final ProvinciaDTO 		LC		 = new ProvinciaDTO("		LC		".trim(),	3	,"		Lecco		".trim());	
	public static final ProvinciaDTO 		LO		 = new ProvinciaDTO("		LO		".trim(),	3	,"		Lodi		".trim());	
	public static final ProvinciaDTO 		BZ		 = new ProvinciaDTO("		BZ		".trim(),	4	,"		Bolzano/Bozen		".trim());	
	public static final ProvinciaDTO 		TN		 = new ProvinciaDTO("		TN		".trim(),	4	,"		Trento		".trim());	
	public static final ProvinciaDTO 		VR		 = new ProvinciaDTO("		VR		".trim(),	5	,"		Verona		".trim());	
	public static final ProvinciaDTO 		VI		 = new ProvinciaDTO("		VI		".trim(),	5	,"		Vicenza		".trim());	
	public static final ProvinciaDTO 		BL		 = new ProvinciaDTO("		BL		".trim(),	5	,"		Belluno		".trim());	
	public static final ProvinciaDTO 		TV		 = new ProvinciaDTO("		TV		".trim(),	5	,"		Treviso		".trim());	
	public static final ProvinciaDTO 		VE		 = new ProvinciaDTO("		VE		".trim(),	5	,"		Venezia		".trim());	
	public static final ProvinciaDTO 		PD		 = new ProvinciaDTO("		PD		".trim(),	5	,"		Padova		".trim());	
	public static final ProvinciaDTO 		RO		 = new ProvinciaDTO("		RO		".trim(),	5	,"		Rovigo		".trim());	
	public static final ProvinciaDTO 		UD		 = new ProvinciaDTO("		UD		".trim(),	6	,"		Udine		".trim());	
	public static final ProvinciaDTO 		GO		 = new ProvinciaDTO("		GO		".trim(),	6	,"		Gorizia		".trim());	
	public static final ProvinciaDTO 		TS		 = new ProvinciaDTO("		TS		".trim(),	6	,"		Trieste		".trim());	
	public static final ProvinciaDTO 		PN		 = new ProvinciaDTO("		PN		".trim(),	6	,"		Pordenone		".trim());	
	public static final ProvinciaDTO 		IM		 = new ProvinciaDTO("		IM		".trim(),	7	,"		Imperia		".trim());	
	public static final ProvinciaDTO 		SV		 = new ProvinciaDTO("		SV		".trim(),	7	,"		Savona		".trim());	
	public static final ProvinciaDTO 		GE		 = new ProvinciaDTO("		GE		".trim(),	7	,"		Genova		".trim());	
	public static final ProvinciaDTO 		SP		 = new ProvinciaDTO("		SP		".trim(),	7	,"		La Spezia		".trim());	
	public static final ProvinciaDTO 		PC		 = new ProvinciaDTO("		PC		".trim(),	8	,"		Piacenza		".trim());	
	public static final ProvinciaDTO 		PR		 = new ProvinciaDTO("		PR		".trim(),	8	,"		Parma		".trim());	
	public static final ProvinciaDTO 		RE		 = new ProvinciaDTO("		RE		".trim(),	8	,"		Reggio nell'Emilia		".trim());	
	public static final ProvinciaDTO 		MO		 = new ProvinciaDTO("		MO		".trim(),	8	,"		Modena		".trim());	
	public static final ProvinciaDTO 		BO		 = new ProvinciaDTO("		BO		".trim(),	8	,"		Bologna		".trim());	
	public static final ProvinciaDTO 		FE		 = new ProvinciaDTO("		FE		".trim(),	8	,"		Ferrara		".trim());	
	public static final ProvinciaDTO 		RA		 = new ProvinciaDTO("		RA		".trim(),	8	,"		Ravenna		".trim());	
	public static final ProvinciaDTO 		FC		 = new ProvinciaDTO("		FC		".trim(),	8	,"		Forlì-Cesena		".trim());	
	public static final ProvinciaDTO 		RN		 = new ProvinciaDTO("		RN		".trim(),	8	,"		Rimini		".trim());	
	public static final ProvinciaDTO 		MS		 = new ProvinciaDTO("		MS		".trim(),	9	,"		Massa-Carrara		".trim());	
	public static final ProvinciaDTO 		LU		 = new ProvinciaDTO("		LU		".trim(),	9	,"		Lucca		".trim());	
	public static final ProvinciaDTO 		PT		 = new ProvinciaDTO("		PT		".trim(),	9	,"		Pistoia		".trim());	
	public static final ProvinciaDTO 		FI		 = new ProvinciaDTO("		FI		".trim(),	9	,"		Firenze		".trim());	
	public static final ProvinciaDTO 		LI		 = new ProvinciaDTO("		LI		".trim(),	9	,"		Livorno		".trim());	
	public static final ProvinciaDTO 		PI		 = new ProvinciaDTO("		PI		".trim(),	9	,"		Pisa		".trim());	
	public static final ProvinciaDTO 		AR		 = new ProvinciaDTO("		AR		".trim(),	9	,"		Arezzo		".trim());	
	public static final ProvinciaDTO 		SI		 = new ProvinciaDTO("		SI		".trim(),	9	,"		Siena		".trim());	
	public static final ProvinciaDTO 		GR		 = new ProvinciaDTO("		GR		".trim(),	9	,"		Grosseto		".trim());	
	public static final ProvinciaDTO 		PO		 = new ProvinciaDTO("		PO		".trim(),	9	,"		Prato		".trim());	
	public static final ProvinciaDTO 		PG		 = new ProvinciaDTO("		PG		".trim(),	10	,"		Perugia		".trim());	
	public static final ProvinciaDTO 		TR		 = new ProvinciaDTO("		TR		".trim(),	10	,"		Terni		".trim());	
	public static final ProvinciaDTO 		PU		 = new ProvinciaDTO("		PU		".trim(),	11	,"		Pesaro Urbino		".trim());	
	public static final ProvinciaDTO 		AN		 = new ProvinciaDTO("		AN		".trim(),	11	,"		Ancona		".trim());	
	public static final ProvinciaDTO 		MC		 = new ProvinciaDTO("		MC		".trim(),	11	,"		Macerata		".trim());	
	public static final ProvinciaDTO 		AP		 = new ProvinciaDTO("		AP		".trim(),	11	,"		Ascoli Piceno		".trim());	
	public static final ProvinciaDTO 		VT		 = new ProvinciaDTO("		VT		".trim(),	12	,"		Viterbo		".trim());	
	public static final ProvinciaDTO 		RI		 = new ProvinciaDTO("		RI		".trim(),	12	,"		Rieti		".trim());	
	public static final ProvinciaDTO 		RM		 = new ProvinciaDTO("		RM		".trim(),	12	,"		Roma		".trim());	
	public static final ProvinciaDTO 		LT		 = new ProvinciaDTO("		LT		".trim(),	12	,"		Latina		".trim());	
	public static final ProvinciaDTO 		FR		 = new ProvinciaDTO("		FR		".trim(),	12	,"		Frosinone		".trim());	
	public static final ProvinciaDTO 		AQ		 = new ProvinciaDTO("		AQ		".trim(),	13	,"		L'Aquila		".trim());	
	public static final ProvinciaDTO 		TE		 = new ProvinciaDTO("		TE		".trim(),	13	,"		Teramo		".trim());	
	public static final ProvinciaDTO 		PE		 = new ProvinciaDTO("		PE		".trim(),	13	,"		Pescara		".trim());	
	public static final ProvinciaDTO 		CH		 = new ProvinciaDTO("		CH		".trim(),	13	,"		Chieti		".trim());	
	public static final ProvinciaDTO 		CB		 = new ProvinciaDTO("		CB		".trim(),	14	,"		Campobasso		".trim());	
	public static final ProvinciaDTO 		IS		 = new ProvinciaDTO("		IS		".trim(),	14	,"		Isernia		".trim());	
	public static final ProvinciaDTO 		CE		 = new ProvinciaDTO("		CE		".trim(),	15	,"		Caserta		".trim());	
	public static final ProvinciaDTO 		BN		 = new ProvinciaDTO("		BN		".trim(),	15	,"		Benevento		".trim());	
	public static final ProvinciaDTO 		NA		 = new ProvinciaDTO("		NA		".trim(),	15	,"		Napoli		".trim());	
	public static final ProvinciaDTO 		AV		 = new ProvinciaDTO("		AV		".trim(),	15	,"		Avellino		".trim());	
	public static final ProvinciaDTO 		SA		 = new ProvinciaDTO("		SA		".trim(),	15	,"		Salerno		".trim());	
	public static final ProvinciaDTO 		FG		 = new ProvinciaDTO("		FG		".trim(),	16	,"		Foggia		".trim());	
	public static final ProvinciaDTO 		BA		 = new ProvinciaDTO("		BA		".trim(),	16	,"		Bari		".trim());	
	public static final ProvinciaDTO 		TA		 = new ProvinciaDTO("		TA		".trim(),	16	,"		Taranto		".trim());	
	public static final ProvinciaDTO 		BR		 = new ProvinciaDTO("		BR		".trim(),	16	,"		Brindisi		".trim());	
	public static final ProvinciaDTO 		LE		 = new ProvinciaDTO("		LE		".trim(),	16	,"		Lecce		".trim());	
	public static final ProvinciaDTO 		PZ		 = new ProvinciaDTO("		PZ		".trim(),	17	,"		Potenza		".trim());	
	public static final ProvinciaDTO 		MT		 = new ProvinciaDTO("		MT		".trim(),	17	,"		Matera		".trim());	
	public static final ProvinciaDTO 		CS		 = new ProvinciaDTO("		CS		".trim(),	18	,"		Cosenza		".trim());	
	public static final ProvinciaDTO 		CZ		 = new ProvinciaDTO("		CZ		".trim(),	18	,"		Catanzaro		".trim());	
	public static final ProvinciaDTO 		RC		 = new ProvinciaDTO("		RC		".trim(),	18	,"		Reggio di Calabria		".trim());	
	public static final ProvinciaDTO 		KR		 = new ProvinciaDTO("		KR		".trim(),	18	,"		Crotone		".trim());	
	public static final ProvinciaDTO 		VV		 = new ProvinciaDTO("		VV		".trim(),	18	,"		Vibo Valentia		".trim());	
	public static final ProvinciaDTO 		TP		 = new ProvinciaDTO("		TP		".trim(),	19	,"		Trapani		".trim());	
	public static final ProvinciaDTO 		PA		 = new ProvinciaDTO("		PA		".trim(),	19	,"		Palermo		".trim());	
	public static final ProvinciaDTO 		ME		 = new ProvinciaDTO("		ME		".trim(),	19	,"		Messina		".trim());	
	public static final ProvinciaDTO 		AG		 = new ProvinciaDTO("		AG		".trim(),	19	,"		Agrigento		".trim());	
	public static final ProvinciaDTO 		CL		 = new ProvinciaDTO("		CL		".trim(),	19	,"		Caltanissetta		".trim());	
	public static final ProvinciaDTO 		EN		 = new ProvinciaDTO("		EN		".trim(),	19	,"		Enna		".trim());	
	public static final ProvinciaDTO 		CT		 = new ProvinciaDTO("		CT		".trim(),	19	,"		Catania		".trim());	
	public static final ProvinciaDTO 		RG		 = new ProvinciaDTO("		RG		".trim(),	19	,"		Ragusa		".trim());	
	public static final ProvinciaDTO 		SR		 = new ProvinciaDTO("		SR		".trim(),	19	,"		Siracusa		".trim());	
	public static final ProvinciaDTO 		SS		 = new ProvinciaDTO("		SS		".trim(),	20	,"		Sassari		".trim());	
	public static final ProvinciaDTO 		NU		 = new ProvinciaDTO("		NU		".trim(),	20	,"		Nuoro		".trim());	
	public static final ProvinciaDTO 		CA		 = new ProvinciaDTO("		CA		".trim(),	20	,"		Cagliari		".trim());	
	public static final ProvinciaDTO 		OR		 = new ProvinciaDTO("		OR		".trim(),	20	,"		Oristano		".trim());	
	public static final ProvinciaDTO 		OT		 = new ProvinciaDTO("		OT		".trim(),	20	,"		Olbia-Tempio		".trim());	
	public static final ProvinciaDTO 		OG		 = new ProvinciaDTO("		OG		".trim(),	20	,"		Ogliastra		".trim());	
	public static final ProvinciaDTO 		VS		 = new ProvinciaDTO("		VS		".trim(),	20	,"		Medio Campidano		".trim());	
	public static final ProvinciaDTO 		CI		 = new ProvinciaDTO("		CI		".trim(),	20	,"		Carbonia-Iglesias		".trim());	


	
	static{	
		provincie.add(		AG		);	
		provincie.add(		AL		);	
		provincie.add(		AN		);	
		provincie.add(		AO		);	
		provincie.add(		AP		);	
		provincie.add(		AQ		);	
		provincie.add(		AR		);	
		provincie.add(		AT		);	
		provincie.add(		AV		);	
		provincie.add(		BA		);	
		provincie.add(		BG		);	
		provincie.add(		BI		);	
		provincie.add(		BL		);	
		provincie.add(		BN		);	
		provincie.add(		BO		);	
		provincie.add(		BR		);	
		provincie.add(		BS		);	
		provincie.add(		BZ		);	
		provincie.add(		CA		);	
		provincie.add(		CB		);	
		provincie.add(		CE		);	
		provincie.add(		CH		);	
		provincie.add(		CI		);	
		provincie.add(		CL		);	
		provincie.add(		CN		);	
		provincie.add(		CO		);	
		provincie.add(		CR		);	
		provincie.add(		CS		);	
		provincie.add(		CT		);	
		provincie.add(		CZ		);	
		provincie.add(		EN		);	
		provincie.add(		FC		);	
		provincie.add(		FE		);	
		provincie.add(		FG		);	
		provincie.add(		FI		);	
		provincie.add(		FR		);	
		provincie.add(		GE		);	
		provincie.add(		GO		);	
		provincie.add(		GR		);	
		provincie.add(		IM		);	
		provincie.add(		IS		);	
		provincie.add(		KR		);	
		provincie.add(		LC		);	
		provincie.add(		LE		);	
		provincie.add(		LI		);	
		provincie.add(		LO		);	
		provincie.add(		LT		);	
		provincie.add(		LU		);	
		provincie.add(		MC		);	
		provincie.add(		ME		);	
		provincie.add(		MI		);	
		provincie.add(		MN		);	
		provincie.add(		MO		);	
		provincie.add(		MS		);	
		provincie.add(		MT		);	
		provincie.add(		NA		);	
		provincie.add(		NO		);	
		provincie.add(		NU		);	
		provincie.add(		OG		);	
		provincie.add(		OR		);	
		provincie.add(		OT		);	
		provincie.add(		PA		);	
		provincie.add(		PC		);	
		provincie.add(		PD		);	
		provincie.add(		PE		);	
		provincie.add(		PG		);	
		provincie.add(		PI		);	
		provincie.add(		PN		);	
		provincie.add(		PO		);	
		provincie.add(		PR		);	
		provincie.add(		PT		);	
		provincie.add(		PU		);	
		provincie.add(		PV		);	
		provincie.add(		PZ		);	
		provincie.add(		RA		);	
		provincie.add(		RC		);	
		provincie.add(		RE		);	
		provincie.add(		RG		);	
		provincie.add(		RI		);	
		provincie.add(		RM		);	
		provincie.add(		RN		);	
		provincie.add(		RO		);	
		provincie.add(		SA		);	
		provincie.add(		SI		);	
		provincie.add(		SO		);	
		provincie.add(		SP		);	
		provincie.add(		SR		);	
		provincie.add(		SS		);	
		provincie.add(		SV		);	
		provincie.add(		TA		);	
		provincie.add(		TE		);	
		provincie.add(		TN		);	
		provincie.add(		TO		);	
		provincie.add(		TP		);	
		provincie.add(		TR		);	
		provincie.add(		TS		);	
		provincie.add(		TV		);	
		provincie.add(		UD		);	
		provincie.add(		VA		);	
		provincie.add(		VB		);	
		provincie.add(		VC		);	
		provincie.add(		VE		);	
		provincie.add(		VI		);	
		provincie.add(		VR		);	
		provincie.add(		VS		);	
		provincie.add(		VT		);	
		provincie.add(		VV		);	

	}
	
	public static List<ProvinciaDTO> getProvincie(){
		return provincie;
	}	
	
	public static void main (String[] args){
		for (ProvinciaDTO provincia: provincie){
			String codice = provincia.getCodice();
			System.out.println(codice);
		}
	}
}
