package it.desimone.risiko.torneo.utils;

public enum TipoTavoli {
	
	 DA_4_ED_EVENTUALMENTE_DA_5
	,DA_4_ED_EVENTUALMENTE_DA_3
	,DA_4_ED_EVENTUALMENTE_DA_5_SE_UNO_SOLO_ALTRIMENTI_DA_3
	,DA_4_ED_EVENTUALMENTE_DA_5_SE_UNO_SOLO_ALTRIMENTI_DA_3_COL_MORTO
	,DA_2_ED_EVENTUALMENTE_DA_3
	,DA_3_ED_EVENTUALMENTE_DA_2
	,DA_3_ED_EVENTUALMENTE_DA_2_COL_MORTO
	,DA_2_ED_EVENTUALMENTE_DA_2_COL_MORTO
	,DA_5_ED_EVENTUALMENTE_DA_4
	,DA_5_ED_EVENTUALMENTE_DA_4_COL_MORTO;

	public static boolean tipoTavoloColMorto(TipoTavoli tipoTavoli){
		 return tipoTavoli == DA_4_ED_EVENTUALMENTE_DA_5_SE_UNO_SOLO_ALTRIMENTI_DA_3_COL_MORTO
		     || tipoTavoli == DA_3_ED_EVENTUALMENTE_DA_2_COL_MORTO
		     || tipoTavoli == DA_5_ED_EVENTUALMENTE_DA_4_COL_MORTO
		     || tipoTavoli == DA_2_ED_EVENTUALMENTE_DA_2_COL_MORTO;
	 }
	
}
